# Generated by Django 4.1.3 on 2023-01-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Locale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("deepl_code", models.CharField(blank=True, max_length=5, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("is_translated", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Locale",
                "verbose_name_plural": "Locales",
                "ordering": ("name",),
            },
        ),
    ]
