# Generated by Django 4.1.3 on 2023-04-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0002_remove_config_date_expired_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="value",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
