# Generated by Django 4.1.3 on 2023-04-10 21:20

from django.db import migrations

import apps.config.managers


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0003_alter_config_value"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="config",
            managers=[
                ("objects", apps.config.managers.ConfigManager()),
            ],
        ),
    ]
