# Generated by Django 4.1.3 on 2023-04-10 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0004_alter_config_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="config",
            managers=[],
        ),
    ]
