# Generated by Django 4.1.3 on 2022-11-22 17:36

import uuid
from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfigFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Unique identification",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date of creation"),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date of last update"),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(blank=True, null=True, verbose_name="Delete date"),
                ),
                (
                    "resize_type",
                    models.CharField(
                        choices=[("pixel", "Pixels"), ("percentage", "Percentage")],
                        default="percentage",
                        max_length=50,
                    ),
                ),
                (
                    "resize_percentage",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("resize_width", models.IntegerField(default=0)),
                ("resize_height", models.IntegerField(default=0)),
                (
                    "resize_fit",
                    models.CharField(
                        choices=[
                            ("resize", "Resize"),
                            ("crop", "Crop"),
                            ("resize", "Scale"),
                        ],
                        default="resize",
                        max_length=50,
                    ),
                ),
                (
                    "rename_prefix",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rename_suffix",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("keep_exif", models.BooleanField(default=False)),
                ("fix_orientation", models.BooleanField(default=False)),
                (
                    "image_quality",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("80"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("custom", models.BooleanField(default=False)),
                ("lossless", models.BooleanField(default=True)),
                ("lossy", models.BooleanField(default=False)),
                ("smallest", models.BooleanField(default=False)),
                (
                    "compression_filter",
                    models.CharField(
                        choices=[
                            ("nearest", "Nearest"),
                            ("box", "Box"),
                            ("bilinear", "Bilinear"),
                            ("hamming", "Hamming"),
                            ("bicubic", "Bicubic"),
                            ("lanczos", "Lanczos"),
                        ],
                        default="lanczos",
                        max_length=50,
                    ),
                ),
                ("keep_size", models.BooleanField(default=False)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("own", "-"),
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                        ],
                        default="desktop",
                        max_length=25,
                    ),
                ),
                ("maximum_file_size", models.IntegerField(default=0)),
                (
                    "convert_type",
                    models.CharField(
                        choices=[
                            ("remain", "-"),
                            ("png", "PNG"),
                            ("webp", "WEBP"),
                            ("jpeg", "JPEG"),
                        ],
                        default="remain",
                        max_length=50,
                    ),
                ),
                ("full_optimized_web_package", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
