# Generated by Django 4.1.3 on 2022-11-22 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("initial_files", "0001_initial"),
        ("compression", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compression",
            name="initial_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="initial_files.initialfile",
            ),
        ),
    ]
