# Generated by Django 4.1.3 on 2022-11-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compressed_file", "0001_initial"),
        ("compression", "0002_compression_initial_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="compression",
            name="compressed_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="compressed_file.compressedfile",
            ),
        ),
    ]
