# Generated by Django 4.1.3 on 2022-12-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["position"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["position"],
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
            },
        ),
        migrations.AlterModelManagers(
            name="question",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="topic",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="question",
            name="level",
        ),
        migrations.RemoveField(
            model_name="question",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="question",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="question",
            name="tree_id",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="level",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="tree_id",
        ),
        migrations.AddField(
            model_name="question",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="topic",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
