# Generated by Django 4.1.3 on 2023-05-21 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0002_alter_question_options_alter_topic_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="faq.topic",
            ),
        ),
    ]
