# Generated by Django 4.1.3 on 2023-02-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0005_alter_translation_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="language",
            field=models.CharField(
                choices=[("nl", "Dutch"), ("en", "English")],
                help_text="the language of the translation",
                max_length=32,
                verbose_name="language",
            ),
        ),
    ]
