# Generated by Django 4.1.3 on 2023-02-04 20:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0006_alter_translation_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="object_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="the id of the object to translate",
                verbose_name="object id",
            ),
        ),
    ]
