# Generated by Django 4.1.3 on 2023-02-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0007_alter_translation_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="language",
            field=models.CharField(
                choices=[("nl", "Dutch")],
                help_text="the language of the translation",
                max_length=32,
                verbose_name="language",
            ),
        ),
    ]
