# Generated by Django 4.1.3 on 2023-05-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0008_alter_translation_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="translation",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="translation",
            name="language",
            field=models.CharField(
                choices=[("en", "English")],
                help_text="the language of the translation",
                max_length=32,
                verbose_name="language",
            ),
        ),
    ]
