# Generated by Django 4.1.3 on 2023-05-03 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_page_key_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"verbose_name": "Page", "verbose_name_plural": "Pages"},
        ),
        migrations.AlterModelOptions(
            name="pageelement",
            options={
                "verbose_name": "Page Element",
                "verbose_name_plural": "Page Elements",
            },
        ),
        migrations.AlterModelOptions(
            name="pagetext",
            options={"verbose_name": "Page Text", "verbose_name_plural": "Page Texts"},
        ),
        migrations.RemoveField(
            model_name="page",
            name="page_elements",
        ),
        migrations.AddField(
            model_name="pageelement",
            name="page",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="pages.page",
            ),
            preserve_default=False,
        ),
    ]
