# Generated by Django 4.1.3 on 2023-05-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_alter_page_options_alter_pageelement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="markup_data",
            field=models.TextField(blank=True, null=True, verbose_name="Structured markup data"),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_image",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Meta image"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="meta_description",
            field=models.TextField(blank=True, null=True, verbose_name="Meta description"),
        ),
        migrations.AlterField(
            model_name="page",
            name="meta_keywords",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="Meta keywords"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="meta_title",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=55,
                null=True,
                verbose_name="Meta title",
            ),
        ),
    ]
