# Generated by Django 4.1.3 on 2023-05-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_page_markup_data_page_meta_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageelement",
            name="key_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
