# Generated by Django 4.1.3 on 2023-01-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookie",
            name="state",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=255,
            ),
        ),
    ]
