# Generated by Django 4.1.3 on 2023-05-03 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cookies", "0002_cookie_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cookie",
            options={"verbose_name": "Cookie", "verbose_name_plural": "Cookies"},
        ),
    ]
