# Generated by Django 4.1.3 on 2023-05-21 12:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookies", "0003_alter_cookie_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Unique identification",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date of creation"),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date of last update"),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(blank=True, null=True, verbose_name="Delete date"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Button Text",
                    ),
                ),
            ],
            options={
                "verbose_name": "AdBlock",
                "verbose_name_plural": "AdBlocks",
            },
        ),
    ]
