# Generated by Django 4.1.3 on 2022-11-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compressed_file", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compressedfile",
            name="file",
            field=models.FileField(max_length=255, upload_to=""),
        ),
    ]
